In [2]:
import gym
import numpy as np
import random

# Define the environment

In [4]:
env = gym.make('Taxi-v3')
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



# Initialise the Q-table

We need to know the number of states and all the actions that we can take from a single state to define the Q-table.

In [11]:
action_size = env.action_space.n
state_size = env.observation_space.n

print(f"Action size: {action_size}")
print(f"State size: {state_size}")

Action size: 6
State size: 500


In [12]:
# Now initialise the Q-table with all entries equal to zeros
q_table = np.zeros([state_size, action_size], dtype=float)
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Define hyperparameters

In [13]:
total_episodes = 1000
total_test_episodes = 50       
max_steps = 99                 # Max steps per episode

lr = 0.7
gamma = 0.618                  # Discount factor

# Exploration parameters
epsilon =  1.0                 # Exploration parameter
max_epsilon = 1.0              # Exploration probability in beginning
min_epsilon = 0.01             # Minimum exploration probability
decay_rate = 0.01              # Exponential decay rate for exploration prob

# Q-learning Algorithm

In [19]:
# In each episode:
# 1. Take a action based on exploration or exploitation
# 2. Update the Q-value for that state and action according to Bellman's equation

for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
        
        # if this number > epsilon  --> exploitation 
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(q_table[state, :])
        
        # else take a random action  --> exploration
        else:
            action = env.action_space.sample()
        
        # Take the action (a) and observe the new state (s') and reward (r)
        new_state, reward, done, info = env.step(action)
        
        # Update the old Q-value based on the bellman's equation
        q_table[state, action] = q_table[state, action] + lr * (reward + gamma * np.max(q_table[new_state, :]) 
                                                                - q_table[state, action])
        
        # our new state is state
        state = new_state
        
        # if done then break
        if done:
            break
    
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)

# Use our Q-table to play Taxi

After 1000 episodes, our Q-table can be used as a cheatsheet to play Taxi

In [25]:
env.reset()
rewards = []

for episode in range(total_test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    print("***************************************")
    print("EPISODE ", episode)
    
    for step in range(max_steps):
        env.render()
        # Take the action (index) which has the maximum expected future rewards
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            print("Score ", total_rewards)
            break
        state = new_state

env.close()
print("Average score over time: " + str(sum(rewards) / total_test_episodes))

***************************************
EPISODE  0
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : :_|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G

EPISODE  30
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | :_|
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : :_|
| | : | : |
